# xinitrc 

# Fix dual boot time issue
#sudo timedatectl set-ntp true

# Phisch's version of the picom compositor
phicom -b --config ~/.config/picom/picom.conf > /dev/null 2> /dev/null &
#conky --pause=5 -q

# Set bg and generate lockscreen
setbg /home/druskus/img/bg/fish.jpg &
xautolock -time 10 -locker "betterlockscreen --lock blur" &

$HOME/.config/polybar/launch.sh > /dev/null 2> /dev/null  &

# Disable pc speaker
#  sudo modprobe -r pcspkr 
#xset -b

# Load keybindings
sxhkd & 

# Notification daemon
dunst &

# Speed up keyboard input
xset r rate 300 50 &	

# Load and generate Xresources configs
xrdbr

# Set kb layout and remap escape to capslock
#  can be done in /etc/X11/xorg.conf
setxkbmap es
setxkbmap -option caps:escape

# Set default cursor (so it's not an X while hovering over background)
xsetroot -cursor_name left_ptr

exec bspwm
