#!/bin/sh


# Colored utilities
alias ls='ls --color=auto'
alias grep='grep --colour=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'

alias open="xdg-open"
alias la="ls -a"
alias cats='highlight -O ansi --force'
alias rg="ranger"
alias todo="vim ~/doc/todo.md"
alias vim="nvim"
alias diff="colordiff"

alias wget="wget --hsts-file=\"$XDG_CACHE_HOME/wget-hsts\""

alias rm="rm -i"

# Shows only hidden files (only on current directory)
alias lh="ls -d -1 .?*"

alias fehs="feh --scale-down --auto-zoom"
alias zathura="nohup zathura > /dev/null 2> /dev/null" 


alias tree="tree -C"

alias nvidia-settings="nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings"
alias wget="wget --hsts-file="$XDG_CACHE_HOME"/wget-hsts"

# Black magic
alias sudo='sudo '
alias visudo="EDITOR=nvim visudo"

alias rm='echo "Fuck you"' 
