#!/bin/sh
#
#   double borders
#

outer='0x2f3132'
inner1='0x98c9ee'
inner2='0xd9ace8'

draw() { chwb2 -I "$i" -O "$o" -i "2" -o "8" $@ 2> /dev/null; }

# initial draw, and then subscribe to events
{ echo; bspc subscribe node_geometry node_focus; } |
        while read -r _; do
                i=$inner1 o=$outer draw "$(targets focused)"
                i=$inner2 o=$outer draw "$(targets  normal)"
        done
