#! /bin/sh

#  _                                          
# | |__  ___ _ ____      ___ __ ___  _ __ ___ 
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
# | |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#           |_|                               
#				By Druskus 


# This prevents from loading multiple times the same options
# on reload
bspc rule -r "*"

# We look for a non-laptop monitor to use for default, but use the laptop
# screen (LVDS) if there's nothing else. This is because I assume that if you
# have an extra screen attached to a laptop, you want to use that.
#mainmonitor="$(bspc query --monitors --names | grep -v LVDS | head -n 1)"

#if ! echo "$mainmonitor" | grep LVDS >/dev/null 2>&1; then
#	xrandr --output "$mainmonitor" --auto --output LVDS1 --off
#fi

bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc desktop -f 1

bspc config border_width 2
bspc config window_gap 10
#bspc config top_padding 24	# top_padding I set equal to polybar's height
bspc config focus_follows_pointer true

bspc config split_ratio                   0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config single_monocle                false

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config external_rules_command ~/.config/bspwm/bspwm-colorsrc
# bspc config external_rules_command ~/.config/bspwm/2border

## Custom Rules ## 
bspc rule -a Matplotlib state=floating
bspc rule -a Zathura state=tiled



rm ~/.xsession-errors*
