#! /bin/sh

# --- bspwm-colorsrc ---

xresource(){
  x="$(xrdb -query | grep -E "^(\*|Bspwm)\.${1}")"
  echo "${x##*:?}"
}

# Same thing, 50% faster
# xresource(){
#     while read -r l; do
#         case ${l} in
#         *\*.${1}|Bspwm.${1}*)
#             echo "${l##*:?}"
#             ;;
#         esac
#     done <<EOF
# $(xrdb -query)
# EOF
# }

normal_border_color=$(xresource normal_border_color)
active_border_color=$(xresource active_border_color)
focused_border_color=$(xresource focused_border_color)
presel_feedback_color=$(xresource presel_feedback_color)

[ -z "$normal_border_color" ]   || bspc config normal_border_color    "$normal_border_color"
[ -z "$active_border_color" ]   || bspc config active_border_color    "$active_border_color"
[ -z "$focused_border_color" ]  || bspc config focused_border_color   "$focused_border_color"
[ -z "$presel_feedback_color" ] || bspc config presel_feedback_color  "$presel_feedback_color"
