#! /bin/sh

# --- bspwm-colorsrc ---

# Change: Moved xresource() to ~/.local/bin/scripts/xresq 

normal_border_color=$(xresq normal_border_color Bspwm)
active_border_color=$(xresq active_border_color Bspwm)
focused_border_color=$(xresq focused_border_color Bspwm)
presel_feedback_color=$(xresq presel_feedback_color Bspwm)

[ -z "$normal_border_color" ]   || bspc config normal_border_color    "$normal_border_color"
[ -z "$active_border_color" ]   || bspc config active_border_color    "$active_border_color"
[ -z "$focused_border_color" ]  || bspc config focused_border_color   "$focused_border_color"
[ -z "$presel_feedback_color" ] || bspc config presel_feedback_color  "$presel_feedback_color"

